Update lsdbparse library to avoid prefix comparisons.
openconfig/lsdbparse pull request #3
Opened 2019-08-02 22:32 UTC by robshakir

```
 * (M) pkg/oc
  - Regenerate library to use a stub of the OpenConfig IS-IS model
    rather than the entire structure.
 * (M) *.go
  - Refactor code mechanically to use the new stubbed model.
  - Avoid handling a prefix to ygot, since we know the prefix that
    is to be used ahead of time, such that there is no need for
    ygot to compare values.
```

On this branch:
```
▶ go test -test.bench BenchmarkRenderLSP    
goos: darwin
goarch: amd64
pkg: github.com/openconfig/lsdbparse
BenchmarkRenderLSP/simple_example/usePathElem=false-12         	   30000	     51473 ns/op
BenchmarkRenderLSP/larger_example/usePathElem=false-12         	    5000	    342712 ns/op
BenchmarkRenderLSP/simple_-_pathelem_path/usePathElem=false-12 	   30000	     41426 ns/op
BenchmarkRenderLSP/simple_example/usePathElem=true-12          	   20000	     69185 ns/op
BenchmarkRenderLSP/larger_example/usePathElem=true-12          	    5000	    375799 ns/op
BenchmarkRenderLSP/simple_-_pathelem_path/usePathElem=true-12  	   30000	     56677 ns/op
PASS
ok  	github.com/openconfig/lsdbparse	11.960s
```

On the original codebase:

```
▶ go test -test.bench BenchmarkRenderLSP
goos: darwin
goarch: amd64
pkg: github.com/openconfig/lsdbparse.orig
BenchmarkRenderLSP/simple_example/usePathElem=false-12         	   20000	     77306 ns/op
BenchmarkRenderLSP/larger_example/usePathElem=false-12         	    3000	    493062 ns/op
BenchmarkRenderLSP/simple_-_pathelem_path/usePathElem=false-12 	   20000	     63038 ns/op
BenchmarkRenderLSP/simple_example/usePathElem=true-12          	   20000	     88830 ns/op
BenchmarkRenderLSP/larger_example/usePathElem=true-12          	    3000	    490654 ns/op
BenchmarkRenderLSP/simple_-_pathelem_path/usePathElem=true-12  	   20000	     67027 ns/op
PASS
ok  	github.com/openconfig/lsdbparse.orig	12.385s
```

On the larger example using `PathElem` this gives us an improvement from 490654 ns/op to 375699 ns/op = 23% improvement.

2019-08-02 22:40 UTC, gcsl approved these changes

2019-08-02 23:41 UTC, wenovus requested changes
Could you also update the README that copies the API? Otherwise looks great.
RenderNotifications(*oc.NetworkInstnace_Protocol_Isis_Level_Lsp, ISISRenderArgs)

2019-08-02 23:55 UTC, robshakir commented
Thanks for catching that Wen, updated!

2019-08-03 00:04 UTC, wenovus approved these changes

2019-08-03 00:13 UTC, merged